# Generated by Django 3.0.14 on 2022-08-24 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_customer_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sex',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
