# Generated by Django 3.0.14 on 2022-08-29 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20220828_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='/default.jpg', null=True, upload_to='static/images'),
        ),
    ]
